name: CI
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      scala-versions:  ${{ steps.set-scala-versions.outputs.versions }}
    steps:
      - uses: actions/checkout@v3
      - id: set-scala-versions
        run: |
          scala212=$(grep "scala2.12" project/Dependencies.scala | sed -E 's/.*= //')
          scala213=$(grep "scala2.13" project/Dependencies.scala | sed -E 's/.*= //')
          scala3=$(grep "scala3" project/Dependencies.scala | sed -E 's/.*= //')
          echo "::set-output name=versions::{\"scala\": [${scala212}, ${scala213}, ${scala3}]}"
  build:
    needs:
      - setup
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.setup.outputs.scala-versions) }}
    runs-on: ubuntu-latest
    services:
      fluentd:
        image: fluentd
        ports:
          - 24224:24224
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'sbt'
      - run: sbt ++${{ matrix.scala }} coverage test
      - run: sbt ++${{ matrix.scala }} examples/run
      - run: sbt ++${{ matrix.scala }} coverageReport
        if: ${{ !startsWith(matrix.scala, '3') }}
      - uses: codecov/codecov-action@v3
        if: ${{ !startsWith(matrix.scala, '3') }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unittests
          fail_ci_if_error: true
          verbose: true
  post-build:
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - run: ':'
  scalafmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'sbt'
      - run: sbt scalafmtCheckAll
  scalafix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'sbt'
      - run: sbt "scalafixAll --check"
